#!/usr/bin/env node
// sync-blog.mjs — regenerate src/data/blog.ts from published posts.
//
// Input: JSON array of posts on stdin (or a file path as argv[2]).
//   Each post: { title, excerpt, content, slug, published, created_at }
// Only posts with `published === true` are included, newest first.
//
// Output: rewrites src/data/blog.ts (a typed TS module) with the posts.
// This is the bridge between the WorkBuddy cloud DB ("官网博客" app) and the
// static Astro homepage. After running, commit + push to GitHub so Cloudflare
// Pages rebuilds lunaaastudio.com.
//
// Usage:
//   node scripts/sync-blog.mjs < posts.json
//   node scripts/sync-blog.mjs posts.json

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "data", "blog.ts");

function readPosts() {
  let raw;
  if (process.argv[2]) {
    raw = readFileSync(process.argv[2], "utf8");
  } else {
    raw = readFileSync(0, "utf8");
  }
  const data = JSON.parse(raw);
  const arr = Array.isArray(data) ? data : (data.data || data.rows || []);
  return arr;
}

function slugify(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function dateLabel(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  if (isNaN(d)) return "";
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return `${String(d.getDate()).padStart(2, "0")} ${months[d.getMonth()]} ${d.getFullYear()}`;
}

function esc(s) {
  return String(s ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "");
}

const posts = readPosts()
  .filter((p) => p.published !== false)
  .sort((a, b) => new Date(b.created_at || b.date) - new Date(a.created_at || a.date))
  .map((p) => ({
    slug: p.slug || slugify(p.title),
    title: p.title || "Untitled",
    excerpt: p.excerpt || "",
    content: p.content || "",
    date: (p.created_at || p.date || "").slice(0, 10),
    dateLabel: dateLabel(p.created_at || p.date),
  }));

const lines = posts.map(
  (p) => `  {
    slug: "${esc(p.slug)}",
    title: "${esc(p.title)}",
    excerpt: "${esc(p.excerpt)}",
    content: "${esc(p.content)}",
    date: "${esc(p.date)}",
    dateLabel: "${esc(p.dateLabel)}",
  },`
);

const out = `// Blog posts — single source of truth for the BLOG section on the homepage.
//
// This file is generated by \`scripts/sync-blog.mjs\`, which pulls the latest
// published posts from the WorkBuddy cloud database ("官网博客" app) and rewrites
// this array. Do not hand-edit; edit posts via the admin panel
// (https://lunaaa-blog.app.workbuddy.host/) and re-run the sync.
//
// Each entry maps to one blog card. \`title\`/\`excerpt\`/\`content\` are plain
// text; \`content\` is markdown rendered on the article page.

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string; // markdown body
  date: string; // ISO date, e.g. "2026-09-01"
  dateLabel: string; // display label, e.g. "01 Sep 2026"
}

export const blogPosts: BlogPost[] = [
${lines.join("\n")}
];
`;

writeFileSync(OUT, out, "utf8");
console.log(`Wrote ${posts.length} post(s) to ${OUT}`);
