// Blog posts — single source of truth for the BLOG section on the homepage.
//
// This file is generated by `scripts/sync-blog.mjs`, which pulls the latest
// published posts from the WorkBuddy cloud database ("官网博客" app) and rewrites
// this array. Do not hand-edit; edit posts via the admin panel
// (https://lunaaa-blog.app.workbuddy.host/) and re-run the sync.
//
// Each entry maps to one blog card. `title`/`excerpt`/`content` are plain
// text; `content` is markdown rendered on the article page.

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string; // markdown body
  coverImage: string; // cover image path (e.g. "/blog-covers/x.jpg") or URL
  date: string; // ISO date, e.g. "2026-09-01"
  dateLabel: string; // display label, e.g. "01 Sep 2026"
}

export const blogPosts: BlogPost[] = [
  {
    slug: "designing-game-interfaces-across-pc-console-mobile",
    title: "Designing Game Interfaces Across PC, Console & Mobile",
    excerpt: "Designing game interfaces across PC, console, and mobile is not simply a matter of adapting screen sizes. Each platform introduces different input methods, interaction patterns, viewing distances, and player expectations. This article explores how UI and interaction design should adapt across mouse and keyboard, controller, and touch—from information hierarchy and navigation to input feedback and accessibility—while maintaining a consistent gameplay experience across platforms.",
    content: "Placeholder here",
    coverImage: "/blog-covers/designing-game-interfaces-across-pc-console-mobile.jpg",
    date: "2026-09-14",
    dateLabel: "14 Sep 2026",
  },
];
